graph {
  source = generated
  shape = three-clusters-hub
  node-count = 91
  activation {
    on-ticks = 1
    off-ticks = 2
  }
}

simulation {
  infection-probability = 0.3
  recovery-probability = 0.1
  initial-infected-count = 1
  seed = 42
  runs = 1
}

output {
  dir = "out/scenarios/huj"
  visualization = true
}
