graph {
  source = file
  file = "scenarios/data/grid_10x10_4neigh.csv"
  explicit-node-count = 100
}

simulation {
  infection-probability = 0.3
  recovery-probability = 0.1
  initial-infected-count = 1
  seed = 42
  runs = 1
}

output {
  dir = "out/scenarios/scenario2-grid-10x10"
  visualization = true
}
